<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/app']], [], [], []],
    'ajax_select_session' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionSessionSelect'], [], [['text', '/ajax_select_session']], [], [], []],
    'ajax_select_candidat' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionCandidatSelect'], [], [['text', '/ajax_select_candidat']], [], [], []],
    'ajax_add_competence' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionCompetence'], [], [['text', '/ajax_add_competence']], [], [], []],
    'ajax_add_ccp' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionCcp'], [], [['text', '/ajax_add_ccp']], [], [], []],
    'ajax_add_jour' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionJour'], [], [['text', '/ajax_add_jour']], [], [], []],
    'ajax_add_habilitation' => [[], ['_controller' => 'App\\Controller\\AppController::ajaxActionHabilitation'], [], [['text', '/ajax_add_habilitation']], [], [], []],
    'audit' => [[], ['_controller' => 'App\\Controller\\AuditController::index'], [], [['text', '/audit']], [], [], []],
    'conception' => [[], ['_controller' => 'App\\Controller\\ConceptionController::index'], [], [['text', '/conception']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'entreprise' => [[], ['_controller' => 'App\\Controller\\EntrepriseController::index'], [], [['text', '/entreprise']], [], [], []],
    'formation' => [[], ['_controller' => 'App\\Controller\\FormationController::index'], [], [['text', '/formation']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'jury' => [[], ['_controller' => 'App\\Controller\\JuryController::index'], [], [['text', '/jury']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'stage' => [[], ['_controller' => 'App\\Controller\\StageController::index'], [], [['text', '/stage']], [], [], []],
    'ajouter' => [[], ['_controller' => 'App\\Controller\\AppController::try'], [], [['text', '/app/ajouter']], [], [], []],
];
