<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE1CjLbE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE1CjLbE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerE1CjLbE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerE1CjLbE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerE1CjLbE\App_KernelProdContainer([
    'container.build_hash' => 'E1CjLbE',
    'container.build_id' => '59f80274',
    'container.build_time' => 1639683410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE1CjLbE');
