<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Titre extends \App\Entity\Titre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'libelle_court', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'libelle_long', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_libelle', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_document', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_date_debut', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_date_fin', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'niveau_id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'ccp_id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'habilitations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'libelle_court', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'libelle_long', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_libelle', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_document', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_date_debut', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'referentiel_date_fin', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'niveau_id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'ccp_id', '' . "\0" . 'App\\Entity\\Titre' . "\0" . 'habilitations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Titre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleCourt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleCourt', []);

        return parent::getLibelleCourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleCourt(?string $libelle_court): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleCourt', [$libelle_court]);

        return parent::setLibelleCourt($libelle_court);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleLong(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleLong', []);

        return parent::getLibelleLong();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleLong(?string $libelle_long): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleLong', [$libelle_long]);

        return parent::setLibelleLong($libelle_long);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentielLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentielLibelle', []);

        return parent::getReferentielLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferentielLibelle(?string $referentiel_libelle): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferentielLibelle', [$referentiel_libelle]);

        return parent::setReferentielLibelle($referentiel_libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentielDocument(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentielDocument', []);

        return parent::getReferentielDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferentielDocument(?string $referentiel_document): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferentielDocument', [$referentiel_document]);

        return parent::setReferentielDocument($referentiel_document);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentielDateDebut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentielDateDebut', []);

        return parent::getReferentielDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferentielDateDebut(?string $referentiel_date_debut): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferentielDateDebut', [$referentiel_date_debut]);

        return parent::setReferentielDateDebut($referentiel_date_debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferentielDateFin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferentielDateFin', []);

        return parent::getReferentielDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferentielDateFin(?string $referentiel_date_fin): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferentielDateFin', [$referentiel_date_fin]);

        return parent::setReferentielDateFin($referentiel_date_fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveauId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveauId', []);

        return parent::getNiveauId();
    }

    /**
     * {@inheritDoc}
     */
    public function addNiveauId(\App\Entity\Niveau $niveauId): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNiveauId', [$niveauId]);

        return parent::addNiveauId($niveauId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNiveauId(\App\Entity\Niveau $niveauId): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNiveauId', [$niveauId]);

        return parent::removeNiveauId($niveauId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCcpId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCcpId', []);

        return parent::getCcpId();
    }

    /**
     * {@inheritDoc}
     */
    public function addCcpId(\App\Entity\Ccp $ccpId): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCcpId', [$ccpId]);

        return parent::addCcpId($ccpId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCcpId(\App\Entity\Ccp $ccpId): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCcpId', [$ccpId]);

        return parent::removeCcpId($ccpId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilitations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilitations', []);

        return parent::getHabilitations();
    }

    /**
     * {@inheritDoc}
     */
    public function addHabilitation(\App\Entity\Habilitation $habilitation): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHabilitation', [$habilitation]);

        return parent::addHabilitation($habilitation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHabilitation(\App\Entity\Habilitation $habilitation): \App\Entity\Titre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHabilitation', [$habilitation]);

        return parent::removeHabilitation($habilitation);
    }

}
