<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AppType' shared autowired service.
     *
     * @return \App\Form\AppType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AppType'] = new \App\Form\AppType();
    }
}
