<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CandidatRepository' shared autowired service.
     *
     * @return \App\Repository\CandidatRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CandidatRepository'] = new \App\Repository\CandidatRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
