<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CandidatType' shared autowired service.
     *
     * @return \App\Form\CandidatType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CandidatType'] = new \App\Form\CandidatType();
    }
}
