<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponsableEntrepriseRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ResponsableEntrepriseRepository' shared autowired service.
     *
     * @return \App\Repository\ResponsableEntrepriseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ResponsableEntrepriseRepository'] = new \App\Repository\ResponsableEntrepriseRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
