<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SessionRepository' shared autowired service.
     *
     * @return \App\Repository\SessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SessionRepository'] = new \App\Repository\SessionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
