<?php

namespace ContainerE1CjLbE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTitreRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TitreRepository' shared autowired service.
     *
     * @return \App\Repository\TitreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TitreRepository'] = new \App\Repository\TitreRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
