<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jury extends \App\Entity\Jury implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_1', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_1', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_2', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_2', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_3', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_3', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'sessions', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'utilisateurs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_1', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_1', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_2', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_2', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'nom_jury_3', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'prenom_jury_3', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'sessions', '' . "\0" . 'App\\Entity\\Jury' . "\0" . 'utilisateurs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Jury $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomJury1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomJury1', []);

        return parent::getNomJury1();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomJury1(?string $nom_jury_1): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomJury1', [$nom_jury_1]);

        return parent::setNomJury1($nom_jury_1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomJury1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomJury1', []);

        return parent::getPrenomJury1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomJury1(?string $prenom_jury_1): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomJury1', [$prenom_jury_1]);

        return parent::setPrenomJury1($prenom_jury_1);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomJury2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomJury2', []);

        return parent::getNomJury2();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomJury2(?string $nom_jury_2): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomJury2', [$nom_jury_2]);

        return parent::setNomJury2($nom_jury_2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomJury2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomJury2', []);

        return parent::getPrenomJury2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomJury2(?string $prenom_jury_2): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomJury2', [$prenom_jury_2]);

        return parent::setPrenomJury2($prenom_jury_2);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomJury3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomJury3', []);

        return parent::getNomJury3();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomJury3(?string $nom_jury_3): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomJury3', [$nom_jury_3]);

        return parent::setNomJury3($nom_jury_3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomJury3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomJury3', []);

        return parent::getPrenomJury3();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomJury3(?string $prenom_jury_3): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomJury3', [$prenom_jury_3]);

        return parent::setPrenomJury3($prenom_jury_3);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessions', []);

        return parent::getSessions();
    }

    /**
     * {@inheritDoc}
     */
    public function addSession(\App\Entity\Session $session): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSession', [$session]);

        return parent::addSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSession(\App\Entity\Session $session): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSession', [$session]);

        return parent::removeSession($session);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateurs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateurs', []);

        return parent::getUtilisateurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addUtilisateur(\App\Entity\Utilisateur $utilisateur): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUtilisateur', [$utilisateur]);

        return parent::addUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUtilisateur(\App\Entity\Utilisateur $utilisateur): \App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUtilisateur', [$utilisateur]);

        return parent::removeUtilisateur($utilisateur);
    }

}
