<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ResponsableEntreprise extends \App\Entity\ResponsableEntreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'nom_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'prenom_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'fonction_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'tel_fixe_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'tel_mob_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'entreprise_id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'nom_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'prenom_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'fonction_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'tel_fixe_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'tel_mob_responsable_entreprise', '' . "\0" . 'App\\Entity\\ResponsableEntreprise' . "\0" . 'entreprise_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ResponsableEntreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomResponsableEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomResponsableEntreprise', []);

        return parent::getNomResponsableEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomResponsableEntreprise(?string $nom_responsable_entreprise): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomResponsableEntreprise', [$nom_responsable_entreprise]);

        return parent::setNomResponsableEntreprise($nom_responsable_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomResponsableEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomResponsableEntreprise', []);

        return parent::getPrenomResponsableEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomResponsableEntreprise(?string $prenom_responsable_entreprise): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomResponsableEntreprise', [$prenom_responsable_entreprise]);

        return parent::setPrenomResponsableEntreprise($prenom_responsable_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonctionResponsableEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonctionResponsableEntreprise', []);

        return parent::getFonctionResponsableEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonctionResponsableEntreprise(?string $fonction_responsable_entreprise): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonctionResponsableEntreprise', [$fonction_responsable_entreprise]);

        return parent::setFonctionResponsableEntreprise($fonction_responsable_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelFixeResponsableEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelFixeResponsableEntreprise', []);

        return parent::getTelFixeResponsableEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelFixeResponsableEntreprise(?string $tel_fixe_responsable_entreprise): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelFixeResponsableEntreprise', [$tel_fixe_responsable_entreprise]);

        return parent::setTelFixeResponsableEntreprise($tel_fixe_responsable_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelMobResponsableEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelMobResponsableEntreprise', []);

        return parent::getTelMobResponsableEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelMobResponsableEntreprise(?string $tel_mob_responsable_entreprise): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelMobResponsableEntreprise', [$tel_mob_responsable_entreprise]);

        return parent::setTelMobResponsableEntreprise($tel_mob_responsable_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrepriseId(): ?\App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrepriseId', []);

        return parent::getEntrepriseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrepriseId(?\App\Entity\Entreprise $entreprise_id): \App\Entity\ResponsableEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrepriseId', [$entreprise_id]);

        return parent::setEntrepriseId($entreprise_id);
    }

}
