<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'insee', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nom_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenom_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresse_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'code_postal_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'ville_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'tel_mob_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'habilitation_id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'jury_id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'insee', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nom_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenom_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresse_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'code_postal_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'ville_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'tel_mob_utilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'habilitation_id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'jury_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getInsee(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsee', []);

        return parent::getInsee();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsee(?string $insee): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsee', [$insee]);

        return parent::setInsee($insee);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomUtilisateur', []);

        return parent::getNomUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomUtilisateur(?string $nom_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomUtilisateur', [$nom_utilisateur]);

        return parent::setNomUtilisateur($nom_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomUtilisateur', []);

        return parent::getPrenomUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomUtilisateur(?string $prenom_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomUtilisateur', [$prenom_utilisateur]);

        return parent::setPrenomUtilisateur($prenom_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseUtilisateur', []);

        return parent::getAdresseUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseUtilisateur(?string $adresse_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseUtilisateur', [$adresse_utilisateur]);

        return parent::setAdresseUtilisateur($adresse_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostalUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostalUtilisateur', []);

        return parent::getCodePostalUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostalUtilisateur(?string $code_postal_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostalUtilisateur', [$code_postal_utilisateur]);

        return parent::setCodePostalUtilisateur($code_postal_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleUtilisateur', []);

        return parent::getVilleUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleUtilisateur(?string $ville_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleUtilisateur', [$ville_utilisateur]);

        return parent::setVilleUtilisateur($ville_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelMobUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelMobUtilisateur', []);

        return parent::getTelMobUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelMobUtilisateur(?string $tel_mob_utilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelMobUtilisateur', [$tel_mob_utilisateur]);

        return parent::setTelMobUtilisateur($tel_mob_utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilitationId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilitationId', []);

        return parent::getHabilitationId();
    }

    /**
     * {@inheritDoc}
     */
    public function addHabilitationId(\App\Entity\Habilitation $habilitationId): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHabilitationId', [$habilitationId]);

        return parent::addHabilitationId($habilitationId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHabilitationId(\App\Entity\Habilitation $habilitationId): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHabilitationId', [$habilitationId]);

        return parent::removeHabilitationId($habilitationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getJuryId(): ?\App\Entity\Jury
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuryId', []);

        return parent::getJuryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuryId(?\App\Entity\Jury $jury_id): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuryId', [$jury_id]);

        return parent::setJuryId($jury_id);
    }

}
